### ISSUE TITLE
Preset accounts of each roles are missing

### ISSUE THREAD

**Issue by dh-013** [Bacio001-CCG/Project-Sint-Scholen-Groep-A#16]
* It is preferable to have 1 set of accounts for each role.
* FOR INSTANCE: There is always a John Doe student account, John Moe as dean, Johnny Depp as Admin etc.

**Comment by MikeWhileCoding** [comment]
This should be the case, only the name and the data of the accounts is randomized

**Comment by dh-013** [comment]
I am aware, but we're programmers, we're way too lazy to search up new emails after every refresh :(
